'use strict';

const EN_FACTS = [
  "Octopuses have three hearts, blue blood, and nine brains.",
  "A group of flamingos is called a 'flamboyance.'",
  "Sloths can hold their breath longer than dolphins — up to 40 minutes.",
  "Wombats poop cubes. Scientists are still not entirely sure why.",
  "Honeybees can recognize individual human faces.",
  "Cows have best friends and get visibly stressed when separated from them.",
  "A snail can sleep for three years straight.",
  "Sharks are older than trees by about 50 million years.",
  "The immortal jellyfish (Turritopsis dohrnii) can revert to a juvenile form and never truly die.",
  "Crows hold grudges and can remember a human face for years.",
  "Sea otters hold hands while sleeping so they don't drift apart.",
  "Koala fingerprints are nearly indistinguishable from human ones.",
  "A blue whale's heart is so big a small child could swim through its arteries.",
  "Goats have rectangular pupils, giving them ~320° of vision.",
  "Pigeons can do basic math on par with monkeys.",
  "Polar bear skin is actually black; their fur is translucent, not white.",
  "Octopuses taste with their suckers.",
  "Hummingbirds are the only birds that can fly backwards.",
  "Bats are the only mammals capable of true flight.",
  "Elephants can recognize themselves in a mirror.",
  "A group of pugs is called a 'grumble.'",
  "Dolphins have unique whistles that act like names for each other.",
  "Tardigrades can survive in the vacuum of space.",
  "A shrimp's heart is in its head.",
  "There's a tree in the Americas that explodes when its fruit ripens — the Sandbox tree.",
  "Penguins propose to their mates with a pebble.",
  "A flamingo's pink color comes entirely from what it eats.",
  "A cat's purr vibrates at a frequency that can promote bone healing.",
  "Some turtles can breathe through their butts.",
  "Wood frogs can freeze solid in winter and thaw back to life in spring.",
  "Rats laugh — at ultrasonic frequencies — when tickled.",
  "There are more stars in the observable universe than grains of sand on every beach on Earth.",
  "A day on Venus is longer than a year on Venus.",
  "Neutron stars can spin up to 600 times per second.",
  "Saturn would float if you could find a bathtub big enough — it's less dense than water.",
  "Exoplanet HD 189733b rains glass sideways at 5,400 mph.",
  "The footprints on the Moon will probably last 100 million years.",
  "About 1.3 million Earths could fit inside the Sun.",
  "There's a giant cloud of alcohol floating in space — Sagittarius B2.",
  "Astronauts say space smells like seared steak and welding fumes.",
  "Olympus Mons on Mars is roughly three times the height of Mount Everest.",
  "55 Cancri e is essentially a planet made of diamond.",
  "A teaspoon of neutron star material would weigh about 6 billion tons.",
  "The ISS travels at 17,500 mph and orbits the Earth every ~90 minutes.",
  "Saturn's moon Titan has lakes and rivers — of liquid methane.",
  "Your stomach gets a fresh lining every 3–4 days, or it would digest itself.",
  "Humans share about 50% of their DNA with bananas.",
  "Your nose can distinguish over a trillion different scents.",
  "The human brain runs on roughly 20 watts — about a dim light bulb.",
  "You're about 1 cm taller in the morning than at night.",
  "Your liver can fully regenerate from as little as 25% of itself.",
  "Humans actually glow in the dark — but 1,000× too faintly for our eyes to see.",
  "Stomach acid is strong enough to dissolve metal.",
  "Babies are born with around 100 more bones than adults have.",
  "The longest hiccup attack on record lasted 68 years.",
  "Roughly 8% of human DNA comes from ancient viruses.",
  "Your heart beats around 100,000 times every single day.",
  "Cleopatra lived closer in time to the Moon landing than to the building of the Great Pyramid.",
  "The Eiffel Tower can grow more than 6 inches taller in summer due to thermal expansion.",
  "Oxford University is older than the Aztec Empire.",
  "The shortest war in history lasted 38 minutes — the Anglo-Zanzibar War of 1896.",
  "In 1518, hundreds of people in Strasbourg danced uncontrollably for days. Nobody knows why.",
  "Napoleon was once attacked by a horde of bunnies during a staged hunt.",
  "Vikings sometimes used the bones of fallen enemies as toothpicks.",
  "The Wright brothers' first flight was shorter than the wingspan of a 747.",
  "Honey never spoils — edible 3,000-year-old honey has been found in Egyptian tombs.",
  "The world's oldest known living tree, Methuselah, is over 4,800 years old.",
  "The first computer 'bug' was an actual moth stuck in a Harvard Mark II relay (1947).",
  "QWERTY was designed in part to slow typists down so the typewriter wouldn't jam.",
  "Email predates the World Wide Web by more than 20 years.",
  "The first webcam was invented to watch a coffee pot at Cambridge.",
  "JavaScript was prototyped in just 10 days back in 1995.",
  "The Apollo 11 guidance computer had less power than a modern calculator.",
  "All 500 of the world's top supercomputers run Linux.",
  "The first computer mouse, built in 1964, was made of wood.",
  "About 90% of all the data in human history was created in the last 2 years.",
  "Carrots were originally purple — Dutch farmers bred them orange in the 17th century.",
  "Lobsters were once considered prison food in colonial America.",
  "Peanuts aren't nuts — they're legumes.",
  "Bananas are technically berries; strawberries technically aren't.",
  "Apples float because they're roughly 25% air.",
  "Watermelons are 92% water.",
  "Pineapples take about 2 years to grow a single fruit.",
  "Pomegranates can have over 1,400 seeds inside one fruit.",
  "There are more possible games of chess than atoms in the observable universe.",
  "The Hawaiian alphabet has only 12 letters.",
  "The dot above a lowercase 'i' or 'j' is called a 'tittle.'",
  "The plastic tip on a shoelace is called an 'aglet.'",
  "The fear of long words is, ironically, called 'hippopotomonstrosesquippedaliophobia.'",
  "There is no Roman numeral for zero.",
  "Bananas are slightly radioactive thanks to potassium-40.",
  "Mount Everest grows about 4 mm taller every year.",
  "Iceland has no mosquitoes.",
  "Bubble wrap was originally invented as wallpaper.",
  "The Bible is the most stolen book in the world.",
  "The microwave was invented after a researcher noticed a chocolate bar melting in his pocket.",
  "There's a species of mushroom that glows in the dark.",
  "A jiffy is a real unit of time — 1/100th of a second.",
  "A standard #2 pencil can draw a continuous line about 35 miles long.",
  "The Mona Lisa has no eyebrows — at the time, it was fashionable to shave them.",
  "Some Hawaiian beaches are growing because parrotfish poop white sand.",
  "Cats can't taste sweetness — they're missing the gene.",
  "A bolt of lightning is about five times hotter than the surface of the Sun.",
  "The longest English word with all letters in alphabetical order is 'almost.'",
  "There's a town in Norway literally called 'Hell,' and it freezes over every winter.",
  "Mr. Potato Head was the first toy ever advertised on television (1952).",
  "The shortest scheduled commercial flight in the world is 90 seconds long.",
  "The longest place name has 85 letters and belongs to a hill in New Zealand.",
  "Glass takes more than a million years to decompose.",
  "The world's smallest reptile, Brookesia nana, fits on a fingertip.",
  "The Atlantic Ocean widens by about an inch each year.",
  "Sloths can rotate their heads almost 270 degrees.",
  "Sea cucumbers fight by ejecting their internal organs at predators.",
  "Every time you shuffle a deck of cards properly, you're almost certainly creating an order that has never existed before.",
  "There are more synapses in your brain than stars in the Milky Way.",
  "Octopus arms have 'mini-brains' — two-thirds of their neurons are outside the head.",
  "A small percentage of the static on old TVs was leftover radiation from the Big Bang.",
  "The original 'Hello, World!' program appeared in a 1972 Bell Labs tutorial by Brian Kernighan.",
  "Saturn isn't the only ringed planet — Jupiter, Uranus, and Neptune all have rings, just fainter.",
  "There's a basketball-sized fungus in Oregon that's the largest living organism on Earth.",
  "If you yelled non-stop for 8 years, 7 months, and 6 days, you'd produce enough sound energy to heat one cup of coffee.",
  "The unicorn is the national animal of Scotland — officially.",
  "An ostrich's eye is bigger than its brain.",
  "Otters have a pouch of skin under their forearm — they store their favorite rock there.",
  "More people are killed every year by cows than by sharks.",
  "Banging your head against a wall burns about 150 calories per hour. Please don't.",
  "There's a species of ant that explodes itself to defend the colony.",
  "Sharks can detect a single drop of blood in an Olympic-size swimming pool.",
  "If you removed all the empty space from the atoms in every human, all of humanity would fit in a sugar cube.",
  "Tetris causes your brain to release dopamine the same way real-life rewards do.",
  "Air conditioning was originally invented to control humidity in a printing plant, not for comfort.",
  "The 'save' icon in most apps is a floppy disk — a thing many users have never touched.",
  "Polar bears can smell a seal from over 20 miles away.",
  "Velcro was inspired by burrs sticking to a dog's fur.",
  "About 7% of all humans who have ever lived are alive right now.",
  "The strongest muscle in the human body, by force, is the masseter — the jaw muscle.",
  "There's enough gold inside Earth's core to coat the entire planet's surface in a 1.5-foot layer.",
  "The total weight of all the ants on Earth used to roughly equal the weight of all humans. The ratio is shifting.",
  "A lightning bolt is roughly 30,000°C — five times hotter than the surface of the Sun.",
  "The Library of Alexandria probably had fewer books than your phone has free storage.",
  "Walt Disney was famously afraid of mice.",
  "There's a 0% chance you'll ever shuffle the same deck of cards twice in human history.",
  "Honey is the only food that includes all substances necessary to sustain life — even water.",
  "Mosquitoes are attracted to the color blue twice as much as any other color.",
  "Your taste buds are completely replaced every 10–14 days.",
  "The first message sent over the internet was 'lo' — the system crashed before it could finish 'login.'",
  "The Pacific Ocean is shrinking by about 1 inch per year.",
  "The deepest part of the ocean (Challenger Deep) is deeper than Mount Everest is tall.",
  "There's a species of jellyfish so venomous a sting can kill a human in under 5 minutes — the box jellyfish.",
  "The hashtag symbol (#) is technically called an 'octothorpe.'",
  "The original name for Bluetooth was 'PAN' (Personal Area Network).",
  "Pluto hasn't completed a single orbit around the Sun since it was discovered in 1930.",
];

const EN_PHRASES = [
  "six seven.",
  "today's vibe: locked in and shipping.",
  "bestie, the compiler said no crumbs.",
  "you ate that segfault. respectfully.",
  "POV: norminette is watching.",
  "main character energy detected.",
  "delulu but make it valgrind-clean.",
  "skibidi compiler activated.",
  "low-key the cleanest Makefile I've ever seen.",
  "it's giving... pointer arithmetic.",
  "on god, fr fr — write more tests.",
  "the rizzler has entered the chat.",
  "your code is bussin' today, no cap.",
  "gyatt, that's a clean diff.",
  "I'm just a chill dev.",
  "based.",
  "the only thing seg-faulting today is your enemies' code.",
  "manifesting zero leaks today.",
  "that's so brat. that's so 42.",
  "the ratio is mathing.",
  "respectfully, touch the keyboard.",
  "in this house we ./run before we git push.",
  "you woke up and chose violence (against bugs).",
  "we don't talk about the segfault from last Tuesday.",
  "if Norminette can't find a flaw, did the code even happen?",
  "today's forecast: 100% chance of clean compiles.",
  "may your stack never overflow.",
  "may your free()s match your malloc()s.",
];

const FR_FACTS = [
  "Les pieuvres ont trois cœurs, du sang bleu et neuf cerveaux.",
  "Un groupe de flamants roses s'appelle une « flamboyance ».",
  "Les paresseux peuvent retenir leur respiration plus longtemps que les dauphins — jusqu'à 40 minutes.",
  "Les wombats font des crottes cubiques. Les scientifiques cherchent encore exactement pourquoi.",
  "Les abeilles peuvent reconnaître des visages humains.",
  "Les vaches ont des meilleures amies et stressent quand on les sépare.",
  "Un escargot peut dormir trois ans d'affilée.",
  "Les requins existent depuis plus longtemps que les arbres — environ 50 millions d'années de plus.",
  "La méduse Turritopsis dohrnii peut revenir à l'état juvénile : elle est biologiquement immortelle.",
  "Les corbeaux gardent rancune et reconnaissent un visage humain pendant des années.",
  "Les loutres se tiennent la main en dormant pour ne pas dériver.",
  "Les empreintes digitales des koalas sont presque identiques à celles des humains.",
  "Le cœur d'une baleine bleue est si grand qu'un enfant pourrait nager dans ses artères.",
  "Les chèvres ont des pupilles rectangulaires : elles voient sur près de 320°.",
  "Les pigeons savent faire des maths basiques au niveau d'un primate.",
  "La peau de l'ours polaire est noire — sa fourrure est translucide, pas blanche.",
  "Les pieuvres goûtent avec leurs ventouses.",
  "Les colibris sont les seuls oiseaux capables de voler en arrière.",
  "Les chauves-souris sont les seuls mammifères à voler vraiment.",
  "Les éléphants se reconnaissent dans un miroir.",
  "Un groupe de carlins s'appelle un « grumble ».",
  "Les dauphins se donnent des « noms » — un sifflement unique par individu.",
  "Les tardigrades survivent dans le vide spatial.",
  "Le cœur d'une crevette est dans sa tête.",
  "Les manchots offrent un caillou à leur partenaire pour lui faire la cour.",
  "La couleur rose des flamants vient entièrement de ce qu'ils mangent.",
  "Le ronronnement du chat vibre à une fréquence qui aide la régénération osseuse.",
  "Certaines tortues respirent par leur arrière-train.",
  "Les grenouilles des bois peuvent geler complètement l'hiver et redémarrer au printemps.",
  "Les rats rient — en ultrasons — quand on les chatouille.",
  "Il y a plus d'étoiles dans l'univers observable que de grains de sable sur Terre.",
  "Un jour sur Vénus dure plus longtemps qu'une année vénusienne.",
  "Les étoiles à neutrons peuvent tourner 600 fois par seconde.",
  "Saturne flotterait si on trouvait une baignoire assez grande — sa densité est inférieure à celle de l'eau.",
  "Sur la planète HD 189733b, il pleut du verre, à l'horizontale, à 8 700 km/h.",
  "Les empreintes laissées sur la Lune devraient durer environ 100 millions d'années.",
  "Environ 1,3 million de Terres tiendraient dans le Soleil.",
  "Il existe un nuage géant d'alcool dans l'espace : Sagittarius B2.",
  "Selon les astronautes, l'espace sent le steak grillé.",
  "Olympus Mons sur Mars est environ trois fois plus haut que l'Everest.",
  "55 Cancri e est, essentiellement, une planète en diamant.",
  "Une cuillère de matière d'étoile à neutrons pèserait environ 6 milliards de tonnes.",
  "La Station Spatiale file à 28 000 km/h et fait le tour de la Terre toutes les 90 minutes.",
  "Titan, lune de Saturne, possède des lacs… de méthane liquide.",
  "Votre estomac change de muqueuse tous les 3 à 4 jours, sinon il se digérerait lui-même.",
  "L'humain partage environ 50 % de son ADN avec une banane.",
  "Votre nez peut distinguer plus de mille milliards d'odeurs.",
  "Le cerveau humain consomme environ 20 W — comme une ampoule faiblarde.",
  "Vous êtes environ 1 cm plus grand le matin que le soir.",
  "Le foie peut se régénérer entièrement à partir de seulement 25 % de lui-même.",
  "Les humains émettent réellement de la lumière, mais 1 000 fois trop faible pour qu'on la voie.",
  "L'acide de votre estomac peut dissoudre du métal.",
  "Les bébés naissent avec environ 100 os de plus que les adultes.",
  "Le plus long hoquet enregistré a duré 68 ans.",
  "Environ 8 % de l'ADN humain provient d'anciens virus.",
  "Votre cœur bat à peu près 100 000 fois par jour.",
  "Cléopâtre a vécu plus près dans le temps de la mission Apollo 11 que de la construction de la Grande Pyramide.",
  "La tour Eiffel peut grandir de plus de 15 cm en été à cause de la dilatation thermique.",
  "L'université d'Oxford est plus ancienne que l'Empire aztèque.",
  "La guerre la plus courte de l'histoire a duré 38 minutes — anglo-zanzibarite, 1896.",
  "En 1518, à Strasbourg, des centaines de personnes se sont mises à danser sans s'arrêter, pendant des jours.",
  "Napoléon a un jour été attaqué par une horde de lapins lors d'une chasse organisée.",
  "Les Vikings utilisaient parfois des os comme cure-dents.",
  "Le premier vol des frères Wright était plus court que l'envergure d'un Boeing 747.",
  "Le miel ne périme jamais — on a trouvé du miel comestible dans des tombes égyptiennes vieilles de 3 000 ans.",
  "Le premier « bug » informatique était un vrai papillon coincé dans un relais en 1947.",
  "Le clavier QWERTY a été conçu en partie pour ralentir les dactylos et éviter les bourrages.",
  "L'e-mail existait plus de 20 ans avant le Web.",
  "La toute première webcam a été inventée pour surveiller une cafetière à Cambridge.",
  "JavaScript a été prototypé en 10 jours en 1995.",
  "L'ordinateur de bord d'Apollo 11 avait moins de puissance qu'une calculatrice moderne.",
  "Les 500 plus gros supercalculateurs du monde tournent tous sous Linux.",
  "Les carottes étaient originellement violettes — orangées par les Hollandais au XVIIᵉ siècle.",
  "Le homard était autrefois considéré comme une nourriture de prison.",
  "La cacahuète n'est pas une noix — c'est une légumineuse.",
  "Les bananes sont techniquement des baies, pas les fraises.",
  "Les pommes flottent parce qu'elles sont environ 25 % d'air.",
  "Une pastèque, c'est 92 % d'eau.",
  "Un ananas met environ 2 ans à pousser.",
  "Une grenade peut contenir plus de 1 400 graines.",
  "Il existe plus de parties d'échecs possibles que d'atomes dans l'univers observable.",
  "L'alphabet hawaïen ne compte que 12 lettres.",
  "Le point sur le « i » et le « j » s'appelle un « tittle ».",
  "L'embout en plastique d'un lacet s'appelle un « aglet » (ferret).",
  "Il n'existe aucun chiffre romain pour zéro.",
  "Les bananes sont très légèrement radioactives à cause du potassium-40.",
  "L'Everest grandit d'environ 4 mm par an.",
  "L'Islande n'a pas de moustiques.",
  "Le papier bulle a été inventé… comme papier peint.",
  "Le micro-ondes a été inventé après qu'un ingénieur a remarqué qu'une barre chocolatée fondait dans sa poche.",
  "Une « jiffy » est une vraie unité de temps — un centième de seconde.",
  "Un crayon HB classique peut tracer un trait de 56 km.",
  "La Joconde n'a pas de sourcils — la mode de l'époque voulait qu'on les rase.",
  "Les chats ne perçoivent pas le goût sucré — il leur manque le gène.",
  "Un éclair est environ cinq fois plus chaud que la surface du Soleil.",
  "Il existe un village en Norvège qui s'appelle « Hell » et qui gèle chaque hiver.",
  "Le verre met plus d'un million d'années à se décomposer.",
  "Le plus petit reptile au monde tient sur le bout d'un doigt.",
  "Les paresseux peuvent tourner la tête à presque 270°.",
  "Plus de gens meurent chaque année à cause de vaches que de requins.",
  "Le miel est le seul aliment qui contient tout ce qu'il faut pour vivre.",
  "Les requins peuvent détecter une seule goutte de sang dans une piscine olympique.",
  "Les vautours digèrent des bactéries qui tueraient n'importe quel autre animal.",
  "L'océan Atlantique s'élargit d'environ 2,5 cm par an.",
  "Pluton n'a même pas terminé une seule orbite autour du Soleil depuis sa découverte en 1930.",
  "Le symbole « # » s'appelle officiellement un « octothorpe ».",
  "Le premier message envoyé sur Internet a été « lo » — le système a planté avant la fin de « login ».",
];

const FR_PHRASES = [
  "six sept.",
  "vibe du jour : locked in.",
  "respectueusement, le compilateur a dit no crumbs.",
  "POV : la norminette regarde.",
  "énergie de personnage principal détectée.",
  "trop chill ce diff, fr.",
  "skibidi compilateur activé.",
  "le code est bussin aujourd'hui, no cap.",
  "tranquille comme un free() bien placé.",
  "que ton stack ne déborde jamais.",
  "que tes free() égalent toujours tes malloc().",
  "aujourd'hui : 100 % de chance de compile propre.",
  "on ne parle pas du segfault de mardi.",
  "c'est très brat, c'est très 42.",
  "respectueusement, retourne au clavier.",
  "dans cette maison on ./run avant de git push.",
  "tu t'es levé(e) et tu as choisi la violence (envers les bugs).",
  "manifeste zéro fuite mémoire aujourd'hui.",
  "le ratio est mathématique.",
  "based, en français.",
];

function pickIndex(len, exclude) {
  if (len <= 1) return 0;
  let i;
  do {
    i = Math.floor(Math.random() * len);
  } while (i === exclude);
  return i;
}

function pool(lang) {
  if (lang === 'fr') return [...FR_FACTS, ...FR_PHRASES];
  return [...EN_FACTS, ...EN_PHRASES];
}

function isPhraseIndex(lang, idx) {
  const facts = lang === 'fr' ? FR_FACTS : EN_FACTS;
  return idx >= facts.length;
}

function pickMessage(lang, lastIndex) {
  const items = pool(lang);
  const i = pickIndex(items.length, lastIndex);
  return { index: i, text: items[i], isPhrase: isPhraseIndex(lang, i) };
}

module.exports = {
  pickMessage,
  EN_FACTS,
  EN_PHRASES,
  FR_FACTS,
  FR_PHRASES,
};
